nginx:
  container_name: uber-hacks
  restart: always
  image: nginx:alpine
  volumes:
    - ./dist:/usr/share/nginx/html
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/sites-enabled/kratelabs.addxy.com:/etc/nginx/sites-enabled/default
    - /etc/letsencrypt/live/addxy.com/fullchain.pem
    - /etc/letsencrypt/live/addxy.com/privkey.pem
  ports:
    - 80:80
    - 443:443
